kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  labels:
     app: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
